### ISSUE TITLE
How to load raw data?

### ISSUE THREAD

**Issue by thomasaarholt** [quantitativeTEM/StatSTEM#1]
The tutorial is excellent, but leaves a glaring hole for users who wish to apply StatSTEM to their own data. How do I import my own data?

It would be nice if StatSTEM could make use of pre-existing code for importing the common formats for STEM, for instance Gatan's [.dm3/.dm4](https://se.mathworks.com/matlabcentral/fileexchange/43005-read-dm3-and-dm4-image-files) or the TIA [.ser](https://se.mathworks.com/matlabcentral/fileexchange/52488-a=serreader-filename--?focused=3892461&tab=function).

Barring that, a simple instruction for the formatting of either the .mat or .txt files would be much appreciated.

**Comment by quantitativeTEM** [comment]
Dear Thomas,

Thank you for downloading the StatSTEM software and using the tutorial. 

We have implemented a '.ser' reader for TIA files in the latest version of StatSTEM, version 2.1. For Gatan's '.dm3/.dm4' files, a reader will follow in a future release of StatSTEM. For now, when opening in digital micrograph your image, you can save them as a text file. This file is suitable for StatSTEM.

We hope this helps

**Comment by karelvandenbos** [comment]
Dear Thomas,

Thank you for downloading the StatSTEM software and using the tutorial. 

We have implemented a SER-reader for TIA files in the latest version of StatSTEM, version 2.1. For Gatan's .dm3/.dm4 files, a reader will follow in a future release of StatSTEM. For now, when opening in digital micrograph your image, you can save them as a text file. This file is suitable for StatSTEM.

Another option is to use one of the existing readers from the Mathworks community to load raw data files. In a next step, when the file is loaded into MATLAB, you can save the variable containing the image as a .mat file. This file can directly be loaded into StatSTEM

We hope this helps

**Comment by hentr** [comment]
Being able to load .tif files would also be nice.

**Comment by karelvandenbos** [comment]
Thank you for the suggestion, we will include this in the next version (2.2)
