### ISSUE TITLE
errors in fitting model

### ISSUE THREAD

**Issue by Stemmaker** [quantitativeTEM/StatSTEM#10]
Hello, I have been learning your Statstem program for several weeks, and it runs very well when I use the picture in its demo files. However, some errors (i.e. getting wrong model and histogram) occurs after I fit a Gaussian model  to my photo (here the result is):

![1](https://user-images.githubusercontent.com/47026595/54021749-cb826e00-41cb-11e9-949c-049d7f9d4125.jpg)
![2](https://user-images.githubusercontent.com/47026595/54021807-ee148700-41cb-11e9-8911-8f7d7dcf3ef5.jpg)
Please help me, thanks a lot.

**Comment by Stemmaker** [comment]
I'm looking forward to your reply soon.

**Comment by annickdebacker** [comment]
It is difficult to comment on this from the fitted model only, which is clearly not correct. It is easier to see what went wrong from the observations plotted together with the input coordinates and fitted coordinates. I guess that some of the input coordinates are not corresponding to intensity peaks, especially at the edges. This causes that some of the peaks are estimated with negative heights, giving the strange fit. It is very likely that you need to modify your starting peak positions to obtain a good model fit.
