### ISSUE TITLE
Problem of removing background 

### ISSUE THREAD

**Issue by Stemmaker** [quantitativeTEM/StatSTEM#11]
Hello, if I want to count atoms in the picture below by using StatSTEM, is there any ways to remove 
the background of the right atoms?
Thanks a lot.

![110](https://user-images.githubusercontent.com/47026595/55792705-c4fd5400-5af3-11e9-838d-62fb312ca753.jpg)

**Comment by annickdebacker** [comment]
There is no option in StatSTEM to remove a spatially varying background.

**Comment by Stemmaker** [comment]
Thank you a lot. How do I get the number  of  atoms of each atomic columns based on the colormap of atom counts? And I view the properties editor of the exported figure, but the origin CDate is a double array of RGB.

**Comment by annickdebacker** [comment]
If you have the figure showing the atom counts, you can use the data cursor 
![image](https://user-images.githubusercontent.com/30527075/56564127-b14ef480-65ad-11e9-8118-942ccf07a5ce.png). By clicking on the counts in the image, you can see the thickness of each column.
![image](https://user-images.githubusercontent.com/30527075/56564250-ec512800-65ad-11e9-90a9-13fb5af3ff43.png)

**Comment by Stemmaker** [comment]
I'm very grateful to you for all your help!
