### ISSUE TITLE
Unexpected probability curve when fitting MAP model

### ISSUE THREAD

**Issue by xzhang2365** [quantitativeTEM/StatSTEM#16]
When fitting MAP model, according to the principle of MAP theory, the probability curve should be a 
non-linear curve and reach a maximum value at a certain number of atoms in the image. However, in the calculation process, the curve did not stop rising when it reached the exact number of atoms in the image, and kept rising until the maximum detection point. 
This happened in my image processing as well as in the calculation of the example of SrTiO. The probability curve of SrTiO is attached, in which it should have peaked at the thirteenth atomic number. If there is any problem?
![SrTiO1](https://user-images.githubusercontent.com/61769472/78873947-357bdf80-7a7e-11ea-8e74-6b4cfa777e86.png)
![SrTiO2](https://user-images.githubusercontent.com/61769472/78873997-475d8280-7a7e-11ea-8f57-e9c486677b12.png)

**Comment by JFatermans** [comment]
Hi xzhang2365,

Thank you for your comment. The file at following location has been updated and is now available to download: functions/@outputStatSTEM_MAP/outputStatSTEM_MAP.m. This should solve your issue.

Please feel free to contact us if there are any remaining issues.
