### ISSUE TITLE
how to make a projected unit cell

### ISSUE THREAD

**Issue by winston-song** [quantitativeTEM/StatSTEM#17]
Hi, I am not sure if the unit cell is right or not, when I click start indexing, there is an error coming out. my requestion is regarding how to make the projection unit cell.

I have a R-3m space group cell, [001] projection of this cell is perpendicular to the ab plane, so I directly use the exported fractional coordinates, using orginal lattice parameters, a, b, c and gama=120 degree. whether this is right?

[100] projection in orginal cell is not perpendicular to the b axis (alpha=120 degree), do I need to use the rotation matrix to rotate b until alpha=90 degree?

thanks

**Comment by xiangang-Zhou** [comment]
Besides, I want to kown that how to get the Library file,too. Do you  kown the answer? thank you.

**Comment by annickdebacker** [comment]
Thank you for your interest in StatSTEM.

The simulated scattering cross-section values need to be obtained using detailed image simulations (e.g. MULTEM - https://github.com/Ivanlh20/MULTEM/releases). The mat-file should contain a vector containing the SCS values as a function of the number of atoms. Such an example file is given in the example folder by the file Library_PtIr.mat.

**Comment by annickdebacker** [comment]
Examples of projected unit cells can be found in the Database folder. If indexing is not working properly automatically, manually select the reference coordinate and the direction of the a-lattice. If necessary, modifying the update factor can also help to make the indexing more stable. Make sure that all the selected coordinates are on the lattice. Omit coordinates which are e.g. loose atoms which are not really connected to a particle.

I hope these suggestions help to improve the indexing of the atomic columns.
