### ISSUE TITLE
Number of CPU Cores

### ISSUE THREAD

**Issue by MoazW** [quantitativeTEM/StatSTEM#23]
Hi,

When I try fitting using 32 cores, the following error message pops up. By hit and trial, I found that fitting works only when using 11 or fewer cores. Is there a certain limit to how many cores can be used?

I am using the latest release of the software. Matlab version is 2016a.

![Screenshot 2021-08-26 010756](https://user-images.githubusercontent.com/89539652/130834786-ba2f31a0-b979-4436-b460-3f14241be02b.png)

**Comment by ThFriedrich** [comment]
The updates in #24 will fix this issue. However, it is worth noting, that increasing the number of cores further isn't necessarily going to speed things up considerably. This is probably very hardware dependent. It may be worth running such a convergence test for your setup.
![timing_cores](https://user-images.githubusercontent.com/47680554/133771715-5a3006ff-be9d-4146-8998-5846e23d05af.png)
