### ISSUE TITLE
Matlab Toolbox requirements

### ISSUE THREAD

**Issue by thomasaarholt** [quantitativeTEM/StatSTEM#3]
I just tried running the Matlab version at home and only realised it needed the Optimization Toolbox when it gave a lsqnonlin error. 

*Then* I got another error saying I needed to install the Statistics and Machine Learning Toolbox.

It would be nice to list the toolbox requirements for StatSTEM in the readme file. What other toolboxes does StatSTEM depend on?

**Comment by karelvandenbos** [comment]
Thanks for this suggestion!
