### ISSUE TITLE
Error at startup

### ISSUE THREAD

**Issue by oopus111** [quantitativeTEM/StatSTEM#35]
Hello,

I started getting a CTFroot error when opening the software. I have tried reinstalling StatSTEM and MATLAB Runtime Compiler, but I cannot resolve the error.

Do you have any suggestions on how to resolve this issue?

Thanks.
![3M}~00LN(7N9LHA%1TFZA_8](https://github.com/quantitativeTEM/StatSTEM/assets/172698151/9ffdb522-9570-42e3-b4ca-18aef29e3a26)

**Comment by pho-Toms** [comment]
Dear oopus111,

Does the problem still persist? It appears to be documented here: [https://www.mathworks.com/matlabcentral/answers/507962-why-do-i-get-the-error-unrecognized-function-or-variable-ctfroot-when-running-matlabwebappserv](https://www.mathworks.com/matlabcentral/answers/507962-why-do-i-get-the-error-unrecognized-function-or-variable-ctfroot-when-running-matlabwebappserv)

Cheers
