### ISSUE TITLE
Error when loading image

### ISSUE THREAD

**Issue by Dowttti321** [quantitativeTEM/StatSTEM#37]
Dear professor,

I tried load a image, but I couldn't load.
Error messages was like this image.
![スクリーンショット 2024-10-11 195335](https://github.com/user-attachments/assets/81b3c154-52de-49a1-9cfa-21f1077d22d2)
I hope to get your reply.
Thank you.

**Comment by pho-Toms** [comment]
Dear Dowttti321,

Thanks for your message. Can you give us some more details on how this error came about? What file type did you try to load? Note that not all filetypes are supported.
