### ISSUE TITLE
Issue when I try strain analysis in StatSTEM

### ISSUE THREAD

**Issue by PhysXu** [quantitativeTEM/StatSTEM#38]
Hi,

I had an issue when I tried strain analysis in StatSTEM for my graphene STEM imaging.

I input the unit cell like below:
![image](https://github.com/user-attachments/assets/9c3d14ff-8ddb-4333-a193-a8cd6d3b2ece)

Then I use Gaussian functions to fit the atom positions.

However, when I tried Start indexing, it told me an error:
![image](https://github.com/user-attachments/assets/e5f977bd-da38-436d-b15c-dca82d797ab1)

How can I solve it?

The version of my matlab is 2023b.

If it is caused by the incompatible version of matlab, which one need I use?

**Comment by pho-Toms** [comment]
Dear PhysXu, I believe the issue would be that the projected unit cell is not correctly specified. If I throw together the cif-file found [here ](https://github.com/jacobjma/PyQSTEM/blob/master/examples/graphene.cif) and [this tool ](https://github.com/ThFriedrich/atomic_specimen_creation.git) I can create a database file with the following contents which does appear to index the [graphene example](https://github.com/quantitativeTEM/StatSTEM/blob/master/Examples/Example_Graphene_MAP_input.mat) correctly. I hope this also works for your application!

```
Database file for StatSTEM
length_a	4.92
length_b	4.261
length_c	6
angle_ab	90

atoms	x	y
C	0.7500	0.8333
C	0.0000	0.0000
C	0.0000	0.3333
C	0.2500	0.5000
C	0.2500	0.8333
C	0.5000	0.0000
C	0.5000	0.3333
C	0.7500	0.5000

zInfo
C	0.0000
C	0.0000
C	0.0000
C	0.0000
C	0.0000
C	0.0000
C	0.0000
C	0.0000

**Comment by PhysXu** [comment]
Hi, @pho-Toms , thanks very much for your reply.

I did some tests by following your suggestions.

1.1- get peak locations with **Peak-finder routine 1**

1.2- projected unit cell with the Database file you provide

1.3- run fitting routine in **Standard procedure**

However, a new error appeared when I clicked `Start indexing`:
![image](https://github.com/user-attachments/assets/92e9d744-c60b-4bfb-b2cf-0e7380f0d40f)


I also tried the peak-fitting with MAP, it looks to work well

1.1- get peak locations with **Peak-finder routine 1**

1.2- projected unit cell with the Database file you provide

1.3- run fitting routine in **Model selection (MAP)**
 
The error above did not appear when I clicked `Start indexing`.

**Why I only can run `Start indexing` with the MAP fitting?**

I also tried my own data with **Standard procedure**, the same error existed.
![image](https://github.com/user-attachments/assets/da8e9a8d-6fae-42d0-8e9b-d2134b8c23b1)
![image](https://github.com/user-attachments/assets/cac4892f-074f-4945-a87a-ac257282c53c)

As the FOV of my data is a bit large, even I have a 12-Core Processor CPU with 128GB RAM, it is still very slow for the MAP fitting.

I am still waiting for the MAP result for my own data.

Is there any other suggestion for the issue?
It will be appreciated very much.

**Comment by pho-Toms** [comment]
Hi @PhysXu , 

## Answer 1
This warning appears to let you know that perhaps not all atomic positions were indexed (correctly). It may be useful to verify that a suitable reference coordinate was chosen (or select it manually) and that the a and b vectors are found correctly as well. Using the graphene example file and the knowledge that the database file was constructed using this unit cell:
![image](https://github.com/user-attachments/assets/4a2e9b44-a015-40d8-8792-e5f12b9b3774)

choosing the a and b directions accordingly: 
![image](https://github.com/user-attachments/assets/f6c475fc-cad9-4ce0-a920-bcfcb53e3c1e)

I get no issues with the indexation of the peaks.

## Answer 2 
The use of the MAP rule to find the column positions should not affect the indexation (provided that the other peak finder can sufficiently accurately find the peaks). Perhaps not all peaks were found/added when you used the regular peak finder? Or perhaps a better reference and/or a-direction was guessed in the indexation step?

## Answer 3
Unfortunately the MAP rule is indeed quite computationally expensive for large field of views. More details on the MAP rule can be found [here](https://doi.org/10.1016/j.ultramic.2019.02.003). However, I don't think you need this for your data. I suggest looking into the points I wrote for Answer 1 (above) for the analysis of your data where an analysis with the regular peak-finder routine should work.

Hope this helps!
