### ISSUE TITLE
Peak finding only the lower Z columns in an image

### ISSUE THREAD

**Issue by thomasaarholt** [quantitativeTEM/StatSTEM#4]
Currently, I don't think there is a way to select only the lower Z elements in a binary sample. For instance in this sample of ZnSb, there is no way (other than manually clicking) to select the Zn (lighter element) columns:
![image](https://user-images.githubusercontent.com/2721423/31743219-a08621d8-b45a-11e7-99e1-59d1785e6ced.png)

**Comment by thomasaarholt** [comment]
Actually on this - there exists a "import peak locations" function, but I don't know what sort of formatting this file should have, and there doesn't seem to be a "Export peak locations"?
Otherwise I could use other software for finding the positions, and then import a list of those positions.

**Comment by hentr** [comment]
If you already have got the peak coordinates (input and/or fitted coordinates) in StatSTEM, you can save a bunch of data (image plus coordinates?) in a .mat file by the save button under the StatSTEM logo. You can load coordinates again from this .mat file. Though, I have not looked at how it is formated.

**Comment by thomasaarholt** [comment]
Ah cool. I didn't realise more information was saved. That makes sense.

**Comment by karelvandenbos** [comment]
Hi Thomas,
This is also documented in the included manual (page 9). Coordinates can be imported as an (nx2) vector, when positions are defined in Angstom. When saving the StatSTEM file, you can also see the coordinates in MATLAB (load the StatSTEM filem, input coordinates for fitting are given in "input.coordinates" again in Angstrom
