### ISSUE TITLE
Reading issues with Statstem

### ISSUE THREAD

**Issue by clc325** [quantitativeTEM/StatSTEM#5]
Hello,

I've been using this program for about 4months now without any probems. However last night it seems like somehow it stopped working. I am running this in Mac, 2015a Matlab, and when I run the fitting procedure the progress will stop at 25% and never move on. I tried the same images that I've ran before (and got nice fitting results), but still it won't show further progress. I get a warning in matlab command saying " Matrix is close to singular or badly scaled. Results may be inaccurate. > In getLinearPar(line 28), In fitGauss_diffrho(line 246), In fitGauss(line 63), In runFitProgram (line 102)". 

I also tried running this program in my laptop, PC, 2015a Matlab. Here there's another problem: I can load images and do tune parameters but it won't let me do "execute routine". It gives me errors like "Index exceeds dimensions, In RunPeakFinder (line 46) if strcmp(get(h.colorbar(1),'State'),'off')". Which is weird because I was testing on the same image that I used in my other computer that had no problems like this. 

So currently I cannot run it  in any of my computers. I'm very surprised that my MAC that has allowed me to run things nicely with this program is now suddenly on halt... and I'm not good at debugging so I seriously need someone's help.  

Thanks

**Comment by karelvandenbos** [comment]
I'm sorry for the late response, I will look into it and come back to you.

**Comment by clc325** [comment]
Thanks for looking into it. Just to update on things that happened after I wrote this:

1. I completely erased matlab 2015a and downloaded the same version and ran the newest version of StatSTEM. It now works partially, meaning that it would detect heavy atoms, but not the light atoms. Before all this happened, I was able to detect the light atoms without any difficulty. When I try the same dataset which I got nice fitting before, these days it will always fail to locate the light atoms. It seems that the sensitivity has somehow gone down. FYI, it works beautifully on light atoms when you run the peak finder routine, but it crashes/fails to do so when you actually run fitting routine. 

2. Still not working in any of my windows laptops, no matter what the version of the Matlab is.

**Comment by karelvandenbos** [comment]
Just for my understanding, when we are talking about light atoms what kind of image are you analysing (CTEM, HAADF STEM, ABF STEM, etc.). Do I understand it correctly that the peak finder routine in the preparation menu always works and the fitting routine fails. Could you send a screen shot of the input image with coordinates that you are trying to fit?

On windows it still gives the error: "Index exceeds dimensions, In RunPeakFinder (line 46) if strcmp(get(h.colorbar(1),'State'),'off')"? Which version of windows are you running?

**Comment by clc325** [comment]
[statstem_fitting.pptx](https://github.com/quantitativeTEM/StatSTEM/files/1661777/statstem_fitting.pptx)

I'm actually working with ABF images for the most part, so I usually normalize the signals and then reverse the contrast of my images to resemble HAADF images before loading them in StatSTEM. And yes, it always works with peak finder routine but fails in the fitting routine. attached are some results I had using StatSTEM.  

On windows, it still gives the error, and I'm using windows version 10. 

I'm happy to communicate with you via your email, where I can send files for you or discuss ongoing problems.

**Comment by karelvandenbos** [comment]
If it is ok with you, I will try to explain how you can solve this issue via github so other user may also see the solution.

If I'm correct, than you are fitting a Guassian with the same width for every column, while different atomic column types are present. This is probably the reason that the fitting algorithm fails. It is better to define different column types using the dropdown menu next to the button "change type to:". Here, click on "add" and define a new column type. Then click on the button "change type to:" and select a region where column of the new type are present. By defining different column types, the program will find for each column type a optimum width of the modelled Gaussian peak and can therefore model the image better. If this not solves the issue than, I you might help the fitting routine by entering manually a value for the background.

For the windows issue, I never saw this error before on windows 10 (or 7) and MATLAB 2015, 2016, 2017 (2018 is not yet tested). However, I'm currently working on a new updated version of StatSTEM (probably version 3.0). So, if for now it works on a Mac and you can work with StatSTEM than hopefully you can wait for the new release?

I hope this helps for now.

**Comment by clc325** [comment]
I actually tried running STATSTEM for a selected small region only with light atoms, but that didn't work  either. So it looks like mine fails even when it only has one type of atomic column. 

I've also tried to fit the whole region by following your instructions, by defining a different column but my Matlab keeps on crashing because it's out of memory. I'm trying to modify the setups, memory allocation and still trying.. I'll let you know if it works.

While these are going on, can you tell me how to manually set the background level? I would like to try that as well.  

Regarding the windows problem, I'll wait until a newer version of StatSTEM is released. 
thanks a lot!

**Comment by clc325** [comment]
Sorry that my reply got late, I've been trying several things;

I haven't tried using different gaussians before but I already experienced that it would not work when I run StatSTEM on only light atomic columns. Anyways I gave it a try on the whole image and depending on the image quality sometimes it would fail (out of memory problem) or run with several odd looking fitting positions. The best combination that I found is to use different width of gaussians and also use the background value from the light atomic column area. From this I think my previous problem was mainly due to background level that was set too high or too low., although I cannot explain how it worked before without all this. 

If you can think of any other features that I should try please let me know. 

For windows, I'll wait for the new release to come out. 

Thanks a lot for your help!

**Comment by karelvandenbos** [comment]
Hi, we are close to releasing a new version. In the meantime I figured out the problem with the error:
RunPeakFinder (line 46) if strcmp(get(h.colorbar(1),'State'),'off')

Maybe you can have a look at:
https://github.com/quantitativeTEM/StatSTEM/issues/7

Have you been able to fit to other images in the meantime? If not, could you save one of the files before fitting and upload it?
