### ISSUE TITLE
error in windows

### ISSUE THREAD

**Issue by jinwoung** [quantitativeTEM/StatSTEM#7]
Hi I always have this kind of error message when I run the statstem. "Index exceeds dimensions, In RunPeakFinder (line 46) if strcmp(get(h.colorbar(1),'State'),'off')"

I am using windows 10. 
is there any way to solve this problem?

**Comment by karelvandenbos** [comment]
I have tested StatSTEM here on windows 10, I don't get this problem. Could you give a little more details:
- Which MATLAB version are you running?
- Does this error occur directly from the start (loading an image and then running the peak finder routine)?
- In the left top corner, is there an option to insert a colorbar?

**Comment by jinwoung** [comment]
I am using matlab version 2015a.
Image loading is fine but every time I click add or execute routine button this error occurs. 
![statstem](https://user-images.githubusercontent.com/39481713/40426493-2d58b596-5ed6-11e8-9e92-98ce1ee1e5b0.jpg)

**Comment by karelvandenbos** [comment]
Ok, if you hold your mouse on the colorbar symbol on top (which is highlighted in your image), what text does it show? Mine says "Insert Colorbar" as is shown in the attached screen shot:
![image](https://user-images.githubusercontent.com/19427472/40426877-744f0b42-5e9c-11e8-8f33-4904e313e71a.png)

**Comment by jinwoung** [comment]
Oh, I found what was the problem. This shows 'Insert Colorbar' in other language. Thanks a lot for your help!

**Comment by karelvandenbos** [comment]
This gives indeed an error, for other users that have this error. You can make StatSTEM work by updating line 213 in StatSTEM.m. Here, you should replace the text "Insert Colorbar" by the text that is shown if you keep your mouse on the colorbar symbol, shown in the figure in my previous comment.
